name: Client SonarQube Analysis
on:
  push:
    paths:
      - 'packages/simple-react-app/**'
      - '.github/workflows/**'
    branches:
      - master

  pull_request:
    paths:
      - 'packages/simple-react-app/**'
      - '.github/workflows/**'
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: packages/simple-react-app
          args: -Dproject.settings=packages/simple-react-app/sonar-scanner.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET_2 }}
          SONAR_HOST_URL: https://d4ef-171-103-29-110.ngrok-free.app

      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
